### PR TITLE
Add secure connection to ldap (and more) 

### PR DESCRIPTION
**Pull request by maikelpoot**
This PR solves multiple issues:

- support all ldap connection protocols:
  - ldap:// (Default unsecure connection)
  - ldap:// + startTLS (Secure connection using StartTLS) 
  - ldaps:// (Deprecated connection over TLS)
  - ldapi:// (Connection over linux socket)
- support use of public CA certificate for verification of LDAP server
- support running metrics endpoint over HTTPS by providing a PEM certificate chain file and key file

### CODE REVIEW

**Comment by zachfi** [comment]
Nice.  My fork also has TLS: https://github.com/xaque208/openldap_exporter as does #3 form the looks of it.

**Comment by maikelpoot** [comment]
> Nice. My fork also has TLS: https://github.com/xaque208/openldap_exporter as does #3 form the looks of it.

Indeed, but both use DialTLS() which come down to the deprecated _ldaps://domain.tld:636_ protocol, this is different from StartTLS which is a 2 step: `l = ldap.Dial(...); l.startTLS(...)` and uses _ldap://domain.tld:389_ as uri which my use-case required. (Same as the other features :D)

And thnx, used both PR's as inspiration 👍 :)

**Comment by zachfi** [comment]
Excellent.  Hopefully one of these will be merged then.  Calling @tomcz for review.

**Comment by tomcz** [comment]
Thank you, not interested.

**Pull request closed without merging**
