### PR TITLE
Configurable metrics path

### PR DESCRIPTION
**Pull request by sakishrist**
Can we add configurable metrics path?

### CODE REVIEW

**Comment by zachfi** [comment]
The change looks reasonable, though, what's the use case?

**Comment by sakishrist** [comment]
I needed to expose multiple exporters on the same port, and the proxy tool
I can use to do this does not support rewriting the path when passing the
requests to the exporters. So I needed to change the path in the exporters
instead. The rest of the exporters I use support this. This one was missing
the option to configure this.

**Comment by zachfi** [comment]
Ah I see.

**Comment by tomcz** [comment]
Good idea, re-implemented in https://github.com/tomcz/openldap_exporter/commit/d79daa184b29e334b3988efd8fd6a6c2ff4b082f

**Comment by tomcz** [comment]
Released as v2.0

**Pull request closed without merging**
